### ISSUE TITLE
tic-bundle doesn't watch files specified in "Assets"

### ISSUE THREAD

**Issue by elegantiron** [chronoDave/tic-bundle#20]
As title. This means that if you open the Assets file with TIC-80 and edit it, tic-bundle will not see the write and rebuild the bundle.

If you add your assets file to both Files and Assets, tic-bundle will watch the file and re-bundle when it notices a change.

**Comment by chronoDave** [comment]
Fixed in #21, thank you for noticing. It's available in `3.5.2` onwards.
