### ISSUE TITLE
Sprite / map data is overwritten each time the output is generated.

### ISSUE THREAD

**Issue by lenaschimmel** [chronoDave/tic-bundle#9]
I started using tic-bundle recently. I'm using TIC-80 version 0.90.1724 Pro on MacOS. My settings can be [seen here](https://github.com/lenaschimmel/dyker/blob/postjam/.ticbundle.json).

It works as described, which is great, but I strugge to find a practicable workflow.

Whenever I change one of the input source files in my IDE (in this case, VS Code), tic-bundle re-creates the output file as expected. When I change tiles / map / etc. within TIC-80, and save the changes, they are saved to [the lua file](https://github.com/lenaschimmel/dyker/blob/postjam/dyke.lua), which tic-bundle consideres to be the output file. **Next time I make a change in VS Code, tic-bundle overrides the output file, so all changes I made to my sprites / maps / etc. are gone.**

I think when re-generating the output file, tic-bundle should recognize the existing ressource comments, and not overwrite them. I'm talkin about these lines:

```
-- <TILES>
-- 001:3333333434333333333433333333333333333343334333333333433343333333
-- 002:9999999999999989998999999999999999999989999999999899989999999999
-- 003:eeeeedeeeeeefdeeeeeffdeeddddddddeedeeeeeefdeeeeeffdeeeeedddddddd
-- 005:65665566776476763773473737333433343333433343343434334f334f333333
...
```

Is there some option that I missed, or does tic-bundle assume another workflow?

**Comment by chronoDave** [comment]
Thank you for the very detailed issue description!

I downloaded your repo and tried to understand the issue you're describing. If I'm correct, you're taking these steps:

1) Create source files in src
2) Bundle these files into your output file, `dyke.lua`
3) Editing the **output** file
4) Losing your changes when you edit your source files

If so, then yes, tic-bundle assumes your output file is always generated, never edited. I noticed your sprites are defined in `src/main.lua` so you'd load that into TIC-80 and change the sprites there if you want to see them in your bundled file.

I hope this answers your question, if not, please let me know.

**Comment by Kyratech** [comment]
I use tic-bundle for my project and this is my workflow for working with this behaviour:

1. In my source files, I created a new file `metadata.lua`.
2. I added `metadata.lua` to the end of the files list in `.ticbundle.json`.
3. When I edit any assets in my project, I save it as a separate file from `build.lua`, called `meta.lua`.
4. I copy the asset comments from `meta.lua` into `metadata.lua`.
5. tic-bundle notices one of the source files has updated, so a rebuild is triggered and the new metadata is incorporated into the new version of `build.lua`.
6. I re-load `build.lua` in TIC-80.

Now that I've established this workflow, I find that it's pretty usable.

I would be in favour of an optional feature that prevents overwriting the metadata though, because it would skip all the manual copying and pasting.

**Comment by chronoDave** [comment]
> I use tic-bundle for my project and this is my workflow for working with this behaviour:
> 
>     1. In my source files, I created a new file `metadata.lua`.
> 
>     2. I added `metadata.lua` to the end of the files list in `.ticbundle.json`.
> 
>     3. When I edit any assets in my project, I save it as a separate file from `build.lua`, called `meta.lua`.
> 
>     4. I copy the asset comments from `meta.lua` into `metadata.lua`.
> 
>     5. tic-bundle notices one of the source files has updated, so a rebuild is triggered and the new metadata is incorporated into the new version of `build.lua`.
> 
>     6. I re-load `build.lua` in TIC-80.
> 
> 
> Now that I've established this workflow, I find that it's pretty usable.
> 
> I would be in favour of an optional feature that prevents overwriting the metadata though, because it would skip all the manual copying and pasting.

I've been playing around in TIC-80 and see the problem you're facing. It's possible to create a blank cart and create graphics, but a loadable file _must_ contain a valid script tag (which gets copied over as well of course). I'll add support and documentation for asset cart (such as graphics and sound) support.

**Comment by chronoDave** [comment]
@lenaschimmel @Kyratech New version (3.3.0) has been published with asset support.

You can now declare files as assets by adding `assets: []` to your configuration, similar to `files: []`. Assets will only have their asset data copied over (all code information is stripped) and files will only have their code information copied.

For example, a file like this:

```LUA
--script: lua

test = 'tic-bundle'

-- test
-- <TILES>
-- 000:0100000010100000010000000000000000000000000000000000000000000000
-- </TILES>

-- <SPRITES>
-- 000:8000000080000000800000008000000080000000800000000000000000000000
-- </SPRITES>

-- <PALETTE>
-- 000:301c00000000000000000000000000000000000000000000009900000000000000000000000000000000000000000000
-- </PALETTE>
```

Would only have

```LUA
--script: lua

test = 'tic-bundle'

-- test
```

copied over if it was declared a file and only

```LUA
-- <TILES>
-- 000:0100000010100000010000000000000000000000000000000000000000000000
-- </TILES>

-- <SPRITES>
-- 000:8000000080000000800000008000000080000000800000000000000000000000
-- </SPRITES>

-- <PALETTE>
-- 000:301c00000000000000000000000000000000000000000000009900000000000000000000000000000000000000000000
-- </PALETTE>
```

if it is declared as an asset. I hope that helps!

**Comment by lenaschimmel** [comment]
Thanks for the quick reaction, @chronoDave!

And thank you @Kyratech for describing a possible workflow. That seems doable, but is not nearly as easy and elegant as I had hoped.

Oh, you just published a version while I was still writing :D I will probably give your solution a shot in a day or two. If it's not what I need, I will probably try to make a quick fork and PR at some time, but currently can't tell _when_ that is going to happen…

**Comment by Kyratech** [comment]
Hi @chronoDave 
Thanks for the quick update! The change is really useful already - hopefully Lena finds it works for her too.
